### ISSUE TITLE
Build failing when using `mvn package` instead of `mvn install` on unreleased branch

### ISSUE THREAD

**Issue by pieterlukasse** [thehyve/cbioportal-docker#43]
When I run the build process with this (only including subset of my dockerfile here):
```
RUN git clone --depth 1 -b chile 'https://github.com/thehyve/cbioportal.git' $PORTAL_HOME
WORKDIR $PORTAL_HOME

RUN mvn -e -DskipTests clean package \
	&& unzip portal/target/cbioportal*.war -d $CATALINA_HOME/webapps/cbioportal \
	&& mv scripts/target/scripts-*.jar /root/ \
	&& mvn clean \
	&& mkdir scripts/target/ \
	&& mv /root/scripts-*.jar scripts/target/
```
then the build fails with following error:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Portal Master ...................................... SUCCESS [02:41 min]
[INFO] model .............................................. SUCCESS [  7.814 s]
[INFO] Portal Business Layer .............................. FAILURE [  2.685 s]
[INFO] persistence ........................................ SKIPPED
[INFO] persistence-api .................................... SKIPPED
[INFO] db-scripts ......................................... SKIPPED
[INFO] persistence-mybatis ................................ SKIPPED
[INFO] service ............................................ SKIPPED
[INFO] Portal Web Layer ................................... SKIPPED
[INFO] security ........................................... SKIPPED
[INFO] security-spring .................................... SKIPPED
[INFO] Portal Core ........................................ SKIPPED
[INFO] cBioPortal ......................................... SKIPPED
[INFO] Portal Scripts ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:24 min
[INFO] Finished at: 2018-12-18T13:48:07+00:00
[INFO] Final Memory: 40M/714M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project business: Could not resolve dependencies for project org.mskcc.cbio:business:jar:c8076e1ca-SNAPSHOT: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project business: Could not resolve dependencies for project org.mskcc.cbio:business:jar:c8076e1ca-SNAPSHOT: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.mskcc.cbio:business:jar:c8076e1ca-SNAPSHOT: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:212)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.mskcc.cbio:model:jar:c8076e1ca-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :business
ERROR: Service 'cbioportal-container' failed to build: The command '/bin/sh -c mvn -e -DskipTests clean package 	&& unzip portal/target/cbioportal*.war -d $CATALINA_HOME/webapps/cbioportal 	&& mv scripts/target/scripts-*.jar /root/ 	&& mvn clean 	&& mkdir scripts/target/ 	&& mv /root/scripts-*.jar scripts/target/' returned a non-zero code: 1
```
Interestingly, when I change the word "package" to "install" in the `mvn` command above, the build process works fine.

**Comment by c4cam** [comment]
This is really interesting. I get the same error. Using install instead of package works, thanks so much for this!

**Comment by fedde-s** [comment]
I don't think people using the version of this docker setup currently in master (v2.1.0) should run into this issue anymore; the `mvn package` command is no longer used in the Dockerfile.

**Comment by fedde-s** [comment]
Besides, I would strongly recommend against replacing the release tag in the clone command by a branch name, as that will likely cause you to run different code than you think you are when the branch changes. To iteratively test out changes to the code, as opposed to using the Dockerfile to ensure a reproducible state, there's [Dockerfile.local](https://github.com/thehyve/cbioportal-docker/blob/v2.1.0/docs/development.md) which uses the `COPY` directive instead.

**Comment by pieterlukasse** [comment]
thanks for the update @fedde-s
