### ISSUE TITLE
Cannot upload data into cBioPortal : Checked DB schema version: (expected: 2.7.3) (found: -1)

### ISSUE THREAD

**Issue by lakhujanivijay** [thehyve/cbioportal-docker#66]
I have installed cBioPortal using docker and so far I was able to work with it. However, recently I ran into an issue (see this https://github.com/thehyve/cbioportal-docker/issues/63) which I got resolved.

But, today I ran into the following issue when I tried to upload a data set. 

**My command**

`
docker run -it --rm --net cbio-net -v "/media/bioinfo:/study:ro" -v "/media/bioinfo:/outdir" -v "/media/bioinfo/portal.properties:/cbioportal/portal.properties:ro" thehyve/cbioportal:v2.0.1-iss5758 metaImport.py -u http://cbioportal-container:8080/cbioportal -s /study --html=/outdir/.html -v -o
`

I could see below error
```
INFO: -: Running validation from cBioPortal version 0-unknown-version-SNAPSHOT
DEBUG: -: Requesting cancertypes from portal at 'http://cbioportal-container:8080/cbioportal'
DEBUG: -: Requesting genes from portal at 'http://cbioportal-container:8080/cbioportal'
DEBUG: -: Requesting genesaliases from portal at 'http://cbioportal-container:8080/cbioportal'
DEBUG: -: Requesting genesets from portal at 'http://cbioportal-container:8080/cbioportal'

DEBUG: meta_study.txt: Starting validation of meta file
INFO: meta_study.txt: Validation of meta file complete

DEBUG: meta_fusion.txt: Starting validation of meta file
INFO: meta_fusion.txt: Validation of meta file complete

DEBUG: meta_mutation_file.txt: Starting validation of meta file
INFO: meta_mutation_file.txt: Validation of meta file complete

DEBUG: meta_clinical_sample.txt: Starting validation of meta file
INFO: meta_clinical_sample.txt: Validation of meta file complete

DEBUG: meta_clinical_patient.txt: Starting validation of meta file
INFO: meta_clinical_patient.txt: Validation of meta file complete

DEBUG: data_clinical_sample.txt: Starting validation of file
INFO: data_clinical_sample.txt: Validation of file complete
INFO: data_clinical_sample.txt: Read 110 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_clinical_patient.txt: Starting validation of file
WARNING: data_clinical_patient.txt: Columns OS_MONTHS and/or OS_STATUS not found. Overall survival analysis feature will not be available for this study.
WARNING: data_clinical_patient.txt: Columns DFS_MONTHS and/or DFS_STATUS not found. Disease free analysis feature will not be available for this study.
INFO: data_clinical_patient.txt: Validation of file complete
INFO: data_clinical_patient.txt: Read 110 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_fusion.txt: Starting validation of file
WARNING: data_fusion.txt: lines [3, 5, 7, (1046 more)]: Duplicate entry in fusion data.; values encountered: ['BRAF	673	K80130654	AGTRAP-BRAF (already defined on line 2)', 'BRAF	673	K80130654	CLCN6-BRAF (already defined on line 4)', 'ABL1	25	K80130654	SFPQ-ABL1 (already defined on line 6)', '(322 more)']
WARNING: data_fusion.txt: lines [808, 809]: Entrez gene id is not an integer. This record will not be loaded.; value encountered: 'FOXO4'
INFO: data_fusion.txt: Validation of file complete
INFO: data_fusion.txt: Read 1375 lines. Lines with warning: 1050. Lines with error: 0

DEBUG: merged.maf: Starting validation of file
WARNING: merged.maf: lines [4, 5, 22, (339 more)]: Gene symbol maps to a single Entrez gene id, but is also associated to other genes as an alias. The system will assume the official gene symbol to be the intended one.; values encountered: ['SF3B1', 'KRAS']
WARNING: merged.maf: lines [4, 5, 8, (2875 more)]: No Amino_Acid_Change or HGVSp_Short value. This mutation record will get a generic "MUTATED" flag
INFO: merged.maf: lines [6, 7, 15, (660 more)]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent]; value encountered: 'Silent'
WARNING: merged.maf: lines [358, 359, 906, (36 more)]: Missing value in SWISSPROT column; this column is recommended to make sure that the UniProt canonical isoform is used when drawing Pfam domains in the mutations view.; value encountered: ''
INFO: merged.maf: Validation of file complete
INFO: merged.maf: Read 6502 lines. Lines with warning: 3059. Lines with error: 0

DEBUG: -: Validating case lists

DEBUG: case_lists/cases_sequenced.txt: Starting validation of meta file
INFO: case_lists/cases_sequenced.txt: Validation of meta file complete

INFO: -: Validation of case list folder complete
INFO: -: Validation complete


#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using /cbioportal/scripts/target/scripts-2.0.1-SNAPSHOT.jar

Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
java.sql.SQLException: java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:98)
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:80)
at org.mskcc.cbio.portal.dao.DaoInfo.setVersion(DaoInfo.java:56)
at org.mskcc.cbio.portal.dao.DaoInfo.checkVersion(DaoInfo.java:83)
at org.mskcc.cbio.portal.util.VersionUtil.main(VersionUtil.java:41)
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:95)
... 4 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:344)
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2333)
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
... 7 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at java.net.Socket.connect(Socket.java:538)
at java.net.Socket.<init>(Socket.java:434)
at java.net.Socket.<init>(Socket.java:244)
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:257)
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:294)
... 23 more
Checked DB schema version: (expected: 2.7.3) (found: -1)
Error, probably due to this version of the portal being out of sync with the database. Run the database migration script located at CBIOPORTAL_SRC/core/src/main/scripts/migrate_db.py before continuing.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 147, in <module>
    cbioportalImporter.main(args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 447, in main
    check_version(jvm_args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 164, in check_version
    run_java(*args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 832, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

```

Note that I can still access cBioportal on local host. And the containers are up:

```
bioinfo@bioinfo-pc$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                  PORTS                    NAMES
e61792bfb7da        mysql:5.7                           "docker-entrypoint.s…"   2 days ago          Up 20 hours             3306/tcp, 33060/tcp      cbioDB
bb744455befd        thehyve/cbioportal:v2.0.1-iss5758   "catalina.sh run"        2 days ago          Up 15 minutes           0.0.0.0:8081->8080/tcp   cbioportal-container

```

**Comment by fedde-s** [comment]
The loader says that it can't connect to the database. Try running a fresh cbioDB container with the same settings, and checking whether the settings in the `docker run` command match the database settings in the `portal.properties` file that you're supplying the loader with.

**Comment by fedde-s** [comment]
Does the issue persist if you do that?

**Comment by lakhujanivijay** [comment]
@fedde-s Where do I check the _database settings_  in the `portal.properties` file?

**Comment by fedde-s** [comment]
https://docs.cbioportal.org/2.3-customization/portal.properties-reference#database-settings

For further support requests about the cBioPortal documentation, please contact the mailing list.
